#pragma once

/**
 * @file AWGameMode.h
 * @brief Server-authoritative match orchestration: phase transitions, validation,
 *        simulation execution, and result distribution.
 *
 * Serves both standalone local (hot-seat) and listen-server networked play.
 */

#include "CoreMinimal.h"
#include "GameFramework/GameModeBase.h"
#include "AutomataWar/AI/AWAIController.h"
#include "AutomataWar/Core/Sim/AutomataSimulation.h"
#include "AWMatchTypes.h"
#include "AWGameMode.generated.h"

/**
 * @brief Central authority for Automata War matches.
 *
 * Manages the Programming -> Submission -> Simulation -> ReplayAutopsy cycle.
 * In standalone, two command slots are filled by direct calls.
 * In online, slots map to connected players via PlayerState.
 */
UCLASS(Blueprintable)
class AUTOMATAWAR_API AAWGameMode : public AGameModeBase
{
    GENERATED_BODY()

public:
    /** Configure the authoritative state, controller, player state, and spectator classes. */
    AAWGameMode();

    /** Determine standalone versus network authority when the arena initializes. */
    virtual void InitGame(const FString &MapName, const FString &Options, FString &ErrorMessage) override;
    /** Assign the next stable command slot to a newly connected player. */
    virtual void PostLogin(APlayerController *NewPlayer) override;
    /** Convert an online disconnect into a deterministic forfeit and clean logout. */
    virtual void Logout(AController *Exiting) override;

    /** Reset the current standalone world for a fresh local hot-seat match. */
    void BeginLocalMatch();

    /** Reset the standalone world and assign slot 1 to an AI planner. */
    void BeginSinglePlayerMatch(EAWAIDifficulty Difficulty);

    /**
     * @brief Handle a command-list submission for a given slot.
     * @param Slot 0 or 1.
     * @param Commands Ordered tank actions.
     * @return Validation result.
     *
     * This is the single authoritative entry point used by both local
     * direct calls and Server RPCs.
     */
    FAWValidationResult HandleSubmission(int32 Slot, const TArray<EAWCommand> &Commands);

    /** Withdraw a local command slot while the match is still in Programming. */
    FAWValidationResult WithdrawSubmission(int32 Slot);

    /** Force advance to next round (ReplayAutopsy -> Programming). */
    UFUNCTION(BlueprintCallable, Category = "AutomataWar")
    void AdvanceToNextRound();

    /** Submission timer duration in seconds. -1 disables. */
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "AutomataWar")
    float SubmissionTimerSeconds = 180.f;

    /** Whether this is a local standalone match (no net). */
    UPROPERTY(BlueprintReadOnly, Category = "AutomataWar")
    bool bLocalMatch = true;

    /** Whether slot 1 is currently generated by AAWAIController. */
    UPROPERTY(BlueprintReadOnly, Category = "AutomataWar|AI")
    bool bSinglePlayerMatch = false;

    /** Selected planning depth for the current single-player match. */
    UPROPERTY(BlueprintReadOnly, Category = "AutomataWar|AI")
    EAWAIDifficulty AIDifficulty = EAWAIDifficulty::Normal;

protected:
    /** Transition to a new phase with validation. */
    void SetPhase(EAWMatchPhase NewPhase);

    /** Called when both slots have submitted. */
    void OnBothSubmitted();

    /** Run the Core simulation on server. */
    void RunSimulation();

    /** Timer callback for submission deadline. */
    void OnSubmissionTimerExpired();

    /** Spawn the planning-only AI controller when a single-player match needs it. */
    void EnsureAIController();

    /** Generate and submit slot 1 through HandleSubmission after the human submits. */
    FAWValidationResult SubmitAICommands();

    /** Last accepted command list per slot. */
    TArray<EAWCommand> AcceptedCommands[2];

    /** Whether each slot has submitted this round. */
    bool bSlotSubmitted[2] = {false, false};

    /** AP already reserved by each slot's last accepted persistent program. */
    int32 CommittedProgramCosts[2] = {0, 0};

    /** Final arena placement reused as the next round's starting placement. */
    Automata::RoundState PersistentRoundState;

    /** Timer handle for submission deadline. */
    FTimerHandle SubmissionTimerHandle;

    /** Next player slot to assign. */
    int32 NextSlot = 0;

    /** Server-only planner used by single-player slot 1. */
    UPROPERTY(Transient)
    TObjectPtr<AAWAIController> AIController;
};
